"""empty message

Revision ID: 184545ee6cdc
Revises: 
Create Date: 2021-09-17 22:55:42.254654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '184545ee6cdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doors',
    sa.Column('door_id', sa.Integer(), nullable=False),
    sa.Column('door_name', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('door_id')
    )
    op.create_index(op.f('ix_doors_door_name'), 'doors', ['door_name'], unique=True)
    op.create_table('rfidcards',
    sa.Column('card_uid', sa.String(length=60), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('lost', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('card_uid')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('default_role', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default_role'), 'roles', ['default_role'], unique=False)
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('owner_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('avatar_hash', sa.String(length=32), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('passcode_hash', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_owners_email'), 'owners', ['email'], unique=True)
    op.create_index(op.f('ix_owners_owner_name'), 'owners', ['owner_name'], unique=True)
    op.create_table('ownerships',
    sa.Column('ownership_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('doors', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('card_uid', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['card_uid'], ['rfidcards.card_uid'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('ownership_id')
    )
    op.create_table('logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('door', sa.Integer(), nullable=True),
    sa.Column('ownership_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ownership_id'], ['ownerships.ownership_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs')
    op.drop_table('ownerships')
    op.drop_index(op.f('ix_owners_owner_name'), table_name='owners')
    op.drop_index(op.f('ix_owners_email'), table_name='owners')
    op.drop_table('owners')
    op.drop_index(op.f('ix_roles_default_role'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('rfidcards')
    op.drop_index(op.f('ix_doors_door_name'), table_name='doors')
    op.drop_table('doors')
    # ### end Alembic commands ###
